/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void TextBoxChange(GTextField source, GEvent event) { //_CODE_:TextBox:338386:

  if(event == GEvent.ENTERED && !(TextBox.getText().equals("")) ) {   
    msgs += (TextBox.getText() + "\n");
    messages.setTextAlign(GAlign.RIGHT,null);
    messages.setText(msgs);
    TextBox.setText("");
    log = split(msgs, "\n");  
    // Writes the strings to a file, each on a separate line
    saveStrings("data/messages.txt", log);

    
    
  }
} //_CODE_:TextBox:338386:

public void goMessage(GButton source, GEvent event) { //_CODE_:messageTab:576134:
  println("messageTab - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:messageTab:576134:

public void goSettings(GButton source, GEvent event) { //_CODE_:SettingsTab:776413:
  println("SettingsTab - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:SettingsTab:776413:

public void goStats(GButton source, GEvent event) { //_CODE_:StatsTab:339897:
  println("StatsTab - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:StatsTab:339897:

public void messageschange(GTextArea source, GEvent event) { //_CODE_:messages:510315:
  println("messages - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:messages:510315:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("JournE");
  TextBox = new GTextField(this, 0, 600, 300, 60, G4P.SCROLLBARS_NONE);
  TextBox.setPromptText("Press here to send a message...");
  TextBox.setOpaque(true);
  TextBox.addEventHandler(this, "TextBoxChange");
  messageTab = new GButton(this, 0, 0, 100, 30);
  messageTab.setText("Messages");
  messageTab.addEventHandler(this, "goMessage");
  SettingsTab = new GButton(this, 200, 0, 100, 30);
  SettingsTab.setText("Settings");
  SettingsTab.addEventHandler(this, "goSettings");
  StatsTab = new GButton(this, 100, 0, 100, 30);
  StatsTab.setText("Stats");
  StatsTab.addEventHandler(this, "goStats");
  messages = new GTextArea(this, 0, 30, 300, 570, G4P.SCROLLBARS_VERTICAL_ONLY | G4P.SCROLLBARS_AUTOHIDE);
  messages.setOpaque(true);
  messages.addEventHandler(this, "messageschange");
}

// Variable declarations 
// autogenerated do not edit
GTextField TextBox; 
GButton messageTab; 
GButton SettingsTab; 
GButton StatsTab; 
GTextArea messages; 
